### ISSUE TITLE
Use sqlalchemy

### ISSUE THREAD

**Issue by harlowja** [LogicalDash/gorm#1]
It seems like https://pypi.python.org/pypi/graph-alchemy/ is similar (but not maintained). I wonder if this gorm could take over from that library and also use sqlalchemy to gain more backend support. At least something to think about...

**Comment by clayote** [comment]
From the looks of it, graph-alchemy is an extension to the SQLAlchemy ORM, specifically. That won't work for gorm's purposes, because gorm has a particular agenda for how to keep track of changes to the graph, so you can't assume that eg. the Edge class lives in only one table, and each Edge, in one record.

On the other hand, while researching this, I discovered the SQL Expression Language in SQLAlchemy, which I might indeed use. Thanks for the tip.

**Comment by harlowja** [comment]
Sure.

Reason why I brought this up, if u want to respond to any mailing list stuff for openstack.

http://lists.openstack.org/pipermail/openstack-dev/2014-September/046349.html

**Comment by clayote** [comment]
OK, I've started a new branch "alchemy" that will try to use SQLAlchemy for everything if you have it installed, falling back to plain sqlite3 otherwise. It's kind of inconvenient for me to test this on other database backends so if you have the time for that it'd be great.

**Comment by harlowja** [comment]
Sure I'll give it a try on postgresql and mysql next week  :smile:

**Comment by clayote** [comment]
Any luck?

**Comment by harlowja** [comment]
Will try this week; keep on getting stuck with other things. Thanks for the reminder. :smile:

**Comment by clayote** [comment]
FYI the latest work on master includes the sqlalchemy compatibility bits.
